name: Linter

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Change to Specific Directory
        working-directory: /Api_Rest
        run: cd working-directory
          # You are now in the specified directory
          # Run any commands or scripts you need he

      - name: Install Dependencies
        run: yarn install

      - name: Run Linter
        run: yarn lint
